function chgCnt(page){
	switch(page){
		case 'home': {
				$('main').html("<div id='home-content'><div id='box'><b id='imie'>Jan Nowak</b><br/><p>Profesjonalny programista_</p><div class='przycisk' id='omnie' onclick='chgCnt(\"aboutme\")'><b>Dowiedz się więcej</b></div></div><div id='boxbar'></div><div id='imgbox'></div></div>");
			break;
		}
		
		case 'aboutme': {
				$('main').html("<div id='aboutme-content'><div id='ja'><a class='fancybox' href='me.jpg'><img src='me.jpg'></a></div><div id='opis'><p id='span1'>Jan Nowak</p><p id='span2'>&nbsp;Programista, biegacz, entuzjasta technologii</p><p id='span3'>Hej, jestem Janek. Jestem doświadczonym programistą i mieszkam we Wrocławiu. Poza podążaniem ścieżką mojej kariery, hobbistycznie zajmuję się bieganiem. To dwa główne zainteresowania, którym poświęciłem swoje całe życie.<br/><br/>Programowaniem interesowałem się praktycznie od dziecka. Zawsze podobał mi się fakt, że za pomocą kilkudziesięciu linijek kodu można stworzyć coś fajnego. Teraz wiążę tę dziedzinę z moją pracą i wychodzi mi to całkiem nieźle! Przekonaj się sam i zobacz kilka moich projektów na stronie portfolio.<br/><br/>Regularnie aktualizuję swojego bloga, na którym możesz zobaczyć moje poczynania podczas przeróżnych eventów dla biegaczy, a szczególnie eventu \"Cały Wrocław Biega\", którego jestem po części organizatorem. Jeżeli jesteś ciekaw, wpadnij na mojego Facebooka, Instagrama lub Twittera.</p><br/><img class='logo' src='site_logos/facebook.png'><img class='logo' src='site_logos/instagram.png'><img class='logo' src='site_logos/twitter.png'></div></div>");
			break;
		}
		
		case 'portfolio': {
				$('main').html("<script>$(document).ready(function(){$('.fancybox').fancybox({});});</script><div id='portfolio-content'><div id='zaznajomsie'><b>Zaznajom się z moimi projektami:</b></div><div id='projekty'><div class='projekt'><figure><a class='fancybox' href='portfolio_images/img1.jpg'><img src='portfolio_images/img1.jpg' class='portfolioimg'></a><figcaption>Projekt 1</figcaption></figure></div><div class='projekt'><figure><a class='fancybox' href='portfolio_images/img2.jpg'><img src='portfolio_images/img2.jpg' class='portfolioimg'></a><figcaption>Projekt 2</figcaption></figure></div><div class='projekt'><figure><a class='fancybox' href='portfolio_images/img3.jpg'><img src='portfolio_images/img3.jpg' class='portfolioimg'></a><figcaption>Projekt 3</figcaption></figure></div><div class='projekt'><figure><a class='fancybox' href='portfolio_images/img4.jpg'><img src='portfolio_images/img4.jpg' class='portfolioimg'></a><figcaption>Projekt 4</figcaption></figure></div><div class='projekt'><figure><a class='fancybox' href='portfolio_images/img5.jpg'><img src='portfolio_images/img5.jpg' class='portfolioimg'></a><figcaption>Projekt 5</figcaption></figure></div><div class='projekt'><figure><a class='fancybox' href='portfolio_images/img6.jpg'><img src='portfolio_images/img6.jpg' class='portfolioimg'></a><figcaption>Projekt 6</figcaption></figure></div><div class='projekt'><figure><a class='fancybox' href='portfolio_images/img7.jpg'><img src='portfolio_images/img7.jpg' class='portfolioimg'></a><figcaption>Projekt 7</figcaption></figure></div><div class='projekt'><figure><a class='fancybox' href='portfolio_images/img8.jpg'><img src='portfolio_images/img8.jpg' class='portfolioimg'></a><figcaption>Projekt 8</figcaption></figure></div></div></div>");
			break;
		}
		
		case 'blog': {
				$('main').html("<div id='blog-content'><div id='posts'><div class='post'><div class='avdiv'><img src='avatar.png'></div><div class='headerdiv'><b>Jan Nowak</b> 14 Czerwca, 15:48</div><div class='textdiv'>Właśnie skończyłem kolejny z moich projektów. Zajął mi trochę czasu, ale było warto. Za niedługo opowiem wam o nim więcej!</div></div><div class='post'><div class='avdiv'><img src='avatar.png'></div><div class='headerdiv'><b>Jan Nowak</b> 02 Czerwca, 13:48</div><div class='textdiv'>Event uważam za udany! Było pełno ludzi, co mnie ogromnie cieszy. Oby taka frekwencja dopisywała następnym razem.</div></div><div class='post'><div class='avdiv'><img src='avatar.png'></div><div class='headerdiv'><b>Jan Nowak</b> 26 Maja, 12:01</div><div class='textdiv'>Przypominam, że już za kilka dni (02.06) odbędzie się kolejne CWB. Z całego serca zapraszam każdego kto ma ochotę przebiec te kilka kilometrów i przy okazji porywalizować z innymi. Zapowiada się nieźle!</div></div><div class='post'><div class='avdiv'><img src='avatar.png'></div><div class='headerdiv'><b>Jan Nowak</b> 21 Maja, 16:32</div><div class='textdiv'>W którymś z poprzednich postów wspomniałem ten nowy framework, którego zacząłem używać. Okazuje się, że jest o wiele wygodniejszy i łatwiejszy w użyciu niż ten poprzedni. Naprawdę znacznie ułatwia to pracę przy kolejnych stronach.</div></div><div class='post'><div class='avdiv'><img src='avatar.png'></div><div class='headerdiv'><b>Jan Nowak</b> 14 Maja, 14:23</div><div class='textdiv'>Moja firma ogłosiła rekrutację nowych junior developerów. Jeżeli znasz się na kodzie i programowanie idzie ci sprawnie, daj im znać! Potrzebujemy dobrych programistów takich jak ty.</div></div></div></div>");
			break;
		}
		
		case 'contact': {
				$('main').html("<div id='contact-content'><div id='left'><div id='mail'><b>Masz jakieś pytania?<br/>Skontaktuj się ze mną!</b><br/><br/><form action='mailto:jannowak@gmail.com'><p><input type='text' placeholder='Imię' id='imie'> <input type='text' placeholder='Nazwisko' id='nazwisko'></p><p><input type='text' placeholder='Numer telefonu' id='telefon'></p><p><textarea placeholder='Tu wpisz swoją wiadomość...'></textarea></p><br/><p><div class='przycisk' id='wyslij' onclick='javascript:this.parentNode.submit()'><b>Wyślij!</b></div></p></form></div></div><div id='right'><div id='map'><b>Lub odwiedź mnie osobiście!</b><br/><br/><iframe src='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2499.3170993628664!2d17.383414615923016!3d51.21323393998933!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x470fe2dea2e60d09%3A0xbb616c35ebdca6e0!2sZesp%C3%B3%C5%82+Szk%C3%B3%C5%82+Ponadgimnazjalnych+im.+Marii+Sk%C5%82odowskiej-Curie!5e0!3m2!1sen!2spl!4v1560278450036!5m2!1sen!2spl' frameborder='0' style='border:0' allowfullscreen></iframe></div></div></div>");
			break;
		}
	}
}
